general:
  project: pretrain_stage1
  run: run_32layers_10B
  seed: 42
  ignore_sanity_checks: true

model:
  make_vocab_size_divisible_by: 128
  model_config:
    is_llama_config: true
    hidden_size: 1024
    num_hidden_layers: 32       
    num_attention_heads: 16
    num_key_value_heads: 4      # GQA
    intermediate_size: 2816
    max_position_embeddings: 2048
    hidden_act: silu
    rms_norm_eps: 1.0e-05
    rope_theta: 10000.0
    tie_word_embeddings: true
    vocab_size: 128256
    initializer_range: 0.02
  init_method:
    std: 0.02

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_style: cosine
    lr_warmup_steps: 100
    lr_warmup_style: linear
    min_decay_lr: 5.0e-05 # Δεν μηδενίζουμε για να συνεχίσουμε Stage 2
  optimizer_factory:
    name: adamW
    torch_adam_is_fused: true
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
  weight_decay: 0.1
  zero_stage: 0

parallelism:
  dp: 4
  tp: 1
  pp: 1
  tp_mode: ALL_REDUCE
  recompute_layer: true

data_stages:
- name: Stage 1 - SlimPajama Packed
  start_training_step: 1
  data:
    dataset:
      dataset_folder: 
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_10B/part_1"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_0"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_1" 
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_2"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_3"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_4"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_5"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_6"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_7"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_8"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_9"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_10"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_11"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_12"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_13"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_14"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_15"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_16"
        - "/leonardo_scratch/large/userexternal/mpeppas0/nanoset_cosmo_5B/part_17"
      dataset_weights:
        - 0.357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0358
        - 0.0358
        - 0.0358
        - 0.0357
        - 0.0357
        - 0.0358
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
        - 0.0357
      vocab_size: 128256
      tokenizer_name: "meta-llama/Meta-Llama-3-8B"
      token_size_in_bytes: 4
    num_loading_workers: 8
    seed: 42

tokens:
  sequence_length: 1024
  micro_batch_size: 4
  batch_accumulation_per_replica: 16
  
  train_steps: 53500
  
  val_check_interval: -1
  limit_val_batches: 0

tokenizer:
  tokenizer_name_or_path: meta-llama/Meta-Llama-3-8B
  tokenizer_max_length: null
  tokenizer_revision: null

checkpoints:
  checkpoint_interval: 2000
  checkpoints_path: /leonardo_scratch/large/userexternal/mpeppas0/ckpts/stage1
  save_initial_state: false
  checkpoints_path_is_shared_file_system: true
  resume_checkpoint_path: /leonardo_scratch/large/userexternal/mpeppas0/ckpts/stage1

logging:
  iteration_step_info_interval: 10
  log_level: info
  log_level_replica: info

