general:
  project: sft_tinyllama_smoke
  run: smoltalk_sft_smoke
  seed: 42
  ignore_sanity_checks: false

model:
  make_vocab_size_divisible_by: 128
  model_config:
    is_llama_config: true
    hidden_size: 2048
    num_hidden_layers: 22
    num_attention_heads: 32
    num_key_value_heads: 4
    intermediate_size: 5632
    max_position_embeddings: 2048
    hidden_act: silu
    rms_norm_eps: 1.0e-05
    rope_theta: 10000.0
    tie_word_embeddings: false
    vocab_size: 32000
    initializer_range: 0.02
  init_method:
    std: 0.02

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 2.0e-05
    lr_decay_style: cosine
    lr_warmup_steps: 20
    lr_warmup_style: linear
    min_decay_lr: 1.0e-06
  optimizer_factory:
    name: adamW
    torch_adam_is_fused: true
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
  weight_decay: 0.1
  zero_stage: 0

parallelism:
  dp: 4
  tp: 1
  pp: 1
  tp_mode: REDUCE_SCATTER

data_stages:
- name: SFT Stage - SmolTalk
  start_training_step: 1
  data:
    dataset:
      hf_dataset_or_datasets: HuggingFaceTB/smol-smoltalk
      hf_dataset_splits: train
      sft_dataloader: true
      dataset_processing_num_proc_per_process: 1
      dataset_overwrite_cache: false
      debug_max_samples: 2000
    num_loading_workers: 4
    seed: 42

tokens:
  sequence_length: 2048
  micro_batch_size: 1
  batch_accumulation_per_replica: 8
  train_steps: 200
  val_check_interval: -1
  limit_val_batches: 0

tokenizer:
  tokenizer_name_or_path: /leonardo_scratch/large/userexternal/mpeppas0/hf_models/tinyllama/chat
  tokenizer_max_length: null
  tokenizer_revision: null

checkpoints:
  checkpoint_interval: 100
  checkpoints_path: /leonardo_scratch/large/userexternal/mpeppas0/ckpts/sft_tinyllama_smoke_20260205
  checkpoints_path_is_shared_file_system: true
  save_initial_state: false
  save_final_state: true
  resume_checkpoint_path: /leonardo_scratch/large/userexternal/mpeppas0/nanotron_models/tinyllama_intermediate
  load_optimizer: false
  load_lr_scheduler: false

logging:
  iteration_step_info_interval: 10
  log_level: info
  log_level_replica: info
